export const CODE21_TYPES = [
  "621 - Stopped in no parking",
  "623 - Stopped on painted island",
  "624 - Stopped near tram stop sign",
  "626 - Parked across driveway",
  "627 - Stopped near safety zone",
  "701 - Overstayed time limit",
  "702 - Meter expired / failed to pay",
  "704 - Stopped in bicycle parking area",
  "705 - Stopped in motorcycle parking area",
  "706 - Parked contrary to parking area requirements",
  "711 - Parked outside bay",
  "715 - Stopped on pedestrian crossing",
  "716 - Stopped before pedestrian crossing",
  "717 - Stopped after pedestrian crossing",
  "718 - Stopped before bicycle crossing",
  "719 - Stopped after bicycle crossing",
  "720 - Stopped in loading zone",
  "721 - Overstayed loading zone",
  "722 - Overstayed loading zone sign time",
  "723 - Stopped in truck zone",
  "726 - Stopped in taxi zone",
  "727 - Stopped in bus zone",
  "728 - Stopped in permit zone",
  "729 - Double parked",
  "730 - Stopped near fire hydrant",
  "735 - Stopped after bus stop sign",
  "736 - Stopped on bicycle path",
  "737 - Stopped on footpath",
  "742 - Stopped near traffic lights intersection",
  "758 - Stopped at yellow line",
] as const;

export type Code21Type = (typeof CODE21_TYPES)[number];
